name: Deploy Auth Service

on:
  push:
    branches:
      - master
    paths:
      - 'packages/auth/**'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create secret.pem file
        run: |
          touch ./packages/auth/secret.pem
          echo "$AUTH_PUBLIC_KEY" >> ./packages/auth/secret.pem
      - run: npm ci
        working-directory: ./packages/auth
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Deploy to AWS
        run: serverless deploy --verbose
        working-directory: ./packages/auth
        env:
          AUTH_PUBLIC_KEY: ${{ secrets.AUTH_PUBLIC_KEY }}
